apiVersion: v1
kind: Service
metadata:
  name: app1
spec:
  selector:
    app: app1
  ports:
  - protocol: "TCP"
    port: 5000
    targetPort: 5000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app1
spec:
  selector:
    matchLabels:
      app: app1
  replicas: 1
  template:
    metadata:
      labels:
        app: app1
    spec:
      containers:
      - name: app1
        image: ghcr.io/s-sajid-ali/remote-debug-python-kubernetes/app1:main
        imagePullPolicy: Always
        env:
          - name: API
            value: "http://app2:5000"
          - name: DEBUGPY_LOG_DIR
            value: "/app/logs"
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: app2
spec:
  selector:
    app: app2
  ports:
  - protocol: "TCP"
    port: 5000
    targetPort: 5000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app2
spec:
  selector:
    matchLabels:
      app: app2
  replicas: 1
  template:
    metadata:
      labels:
        app: app2
    spec:
      containers:
      - name: app2
        image: ghcr.io/s-sajid-ali/remote-debug-python-kubernetes/app2:main
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
